### ISSUE TITLE
开始页面出现了不应该有的十周年的按钮,因为调用不到选项，所以会报错

### ISSUE THREAD

**Issue by LibertyBelief** [mengxinzxz/decadeUI--mx#11]
![Screenshot_2024-02-24-09-23-53-478_com noname shijian](https://github.com/mengxinzxz/decadeUI--mx/assets/159143415/463abca1-8db9-44ca-8411-09191b373395)
开始页面点右上角+出现了不应该有的十周年的按钮,因为调用不到选项，所以会报错

**Comment by LibertyBelief** [comment]
![Screenshot_2024-02-24-09-24-11-176_com noname shijian](https://github.com/mengxinzxz/decadeUI--mx/assets/159143415/ac9b9e93-7e86-466e-9728-cb25d856d1f3)
![Screenshot_2024-02-24-09-24-09-327_com noname shijian](https://github.com/mengxinzxz/decadeUI--mx/assets/159143415/268304cc-8617-4c2f-974c-ed3fc1260e54)

**Comment by mengxinzxz** [comment]
已解决
