### ISSUE TITLE
转换技的“阴“”阳”图标反了

### ISSUE THREAD

**Issue by wxsthuee** [mengxinzxz/decadeUI--mx#12]
<img width="1236" alt="image" src="https://github.com/mengxinzxz/decadeUI--mx/assets/6491355/3ef9e08d-c59e-4c82-b4c0-acd2e45c1eab">

如上图所示，游戏开始时的转换技分支是“阴”，但是图标显示的是“阳”。

**Comment by mengxinzxz** [comment]
无名杀描述的阴阳默认反写
