### ISSUE TITLE
梦诸葛亮问天技能 不能直观判断是否失效。

### ISSUE THREAD

**Issue by chdm1013** [mengxinzxz/decadeUI--mx#16]
打开十周年ui时，梦诸葛亮使用问天不显示用了牌顶的什么牌，这样无法直观判断该技能是否失效，也没个标记表示问天已失效。

**Comment by mengxinzxz** [comment]
后者问题请打开游戏播报功能，前者牵涉的不使用自己区域的牌不显示的bug已修复
