### ISSUE TITLE
自制拓展保存时会导致自制拓展的extension.js格式错误

### ISSUE THREAD

**Issue by TianyaSKY** [mengxinzxz/decadeUI--mx#20]
![image](https://github.com/user-attachments/assets/737fbc72-55d9-4773-a4d4-a062d8e3ed27)
![image](https://github.com/user-attachments/assets/f168d3ee-780b-463c-bfd2-3e4d7efa0923)
版本0.3.3 1.10.14

**Comment by mengxinzxz** [comment]
本体bug，记得昨前天已修复
