### ISSUE TITLE
打开十周年UI之后，星孙尚香【骄豪】错误

### ISSUE THREAD

**Issue by wxsthuee** [mengxinzxz/decadeUI--mx#21]
无法使用拼点牌。
cards.filterInD("d")之后为空。

**Comment by mengxinzxz** [comment]
![image](https://github.com/user-attachments/assets/927694f6-144a-4944-8591-05f002416c9a)
未碰到

**Comment by wxsthuee** [comment]
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/ea31a849-537c-4513-acf7-5f4d0cc3876b">
开启十周年UI时，显示获得“空气”。
游戏版本1.10.14，十周年UI版本0.3.3

**Comment by wxsthuee** [comment]
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/27b25350-8402-47cc-a085-c769a725a284">
关闭十周年UI时，是正常的
