### ISSUE TITLE
进入游戏时扩展报错

### ISSUE THREAD

**Issue by cjk7989** [mengxinzxz/decadeUI--mx#25]
自从下载了大佬9月某次commit之后的扩展后，开始出现这个问题。

无名杀版本：1.10.15.1
![image](https://github.com/user-attachments/assets/dd609312-5474-436f-b41a-0c0bfad30ea3)

无视错误进入游戏后提示：
![image](https://github.com/user-attachments/assets/7fa61a46-161e-46a6-9817-10d4547d9896)

**Comment by mengxinzxz** [comment]
跟进PR版本，否则不要跟进仓库
