### ISSUE TITLE
萌佬 怎么让谋黄忠和张嫙这种武将显示技能花色呢

### ISSUE THREAD

**Issue by sefs6e6e** [mengxinzxz/decadeUI--mx#4]

**Comment by mengxinzxz** [comment]
请根据触发时机自行添加全局技能

**Comment by sefs6e6e** [comment]
> 请根据触发时机自行添加全局技能

该如何操作呢

**Comment by mengxinzxz** [comment]
比如谋黄忠或张璇是出一张牌记录花色，写个useCard时机的全局技能进行标记就行了

**Comment by sefs6e6e** [comment]
> 比如谋黄忠或张璇是出一张牌记录花色，写个useCard时机的全局技能进行标记就行了

没有 我的意思是 还没出牌 到自己回合的时候 同礼 ♣️♥️

**Comment by mengxinzxz** [comment]
去限定获得花色的时机

**Comment by sefs6e6e** [comment]
> 去限定获得花色的时机

好难理解 佬能不能教教 抄个作业

**Comment by sefs6e6e** [comment]
> 去限定获得花色的时机

![Screenshot_2024-01-20-19-51-16-272_com.noname.shijian.jpg](https://github.com/mengxinzxz/decadeUI--mx/assets/135153177/d08cc88d-5da8-4523-b26a-6306e831b27f)

这样 显示花色
同礼 ♣️♥️
