### ISSUE TITLE
十周年ui,挑战模式boss名字错乱可在extension.js文件content: function (config, pack) {后添加以下代码解决

### ISSUE THREAD

**Issue by LibertyBelief** [mengxinzxz/decadeUI--mx#7]
//boss名字样式
			const style_bossName = document.createElement('style');
            const css = "#bosslist > .player > .identity { height: 100%; position: absolute; z-index: 9999; }"+
            "#bosslist > .player > .identity > div { text-align: left; }"+
            ".confirm-box.guan-xing>.content>.card { cursor: pointer; left: 35px; margin: 0; position: absolute; width: 108px; }";
            style_bossName.appendChild(document.createTextNode(css));
            const head = document.head || document.getElementsByTagName('head')[0];
            head.appendChild(style_bossName);

**Comment by mengxinzxz** [comment]
已修
